# Generated by Django 4.2.16 on 2024-09-28 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_type',
        ),
    ]
